language: python
python:
  - 3.6
  - 3.7


branches:
  only:
  - master


matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true


install:
  - pip install pipenv
  - pipenv install --dev


script:
  - pytest -v --cov pytorch_privacy --cov-report term-missing


after_success:
  - coveralls